import { Injectable } from "@angular/core";
import { InMemoryDbService } from "angular-in-memory-web-api";
import { Vehicle } from "../classes/vehicle";
import { Dispatch } from "../classes/dispatch";

@Injectable({
  providedIn: "root",
})
export class VehicleDataService implements InMemoryDbService {
  createDb() {
    let vehicles: Vehicle[] = [
      {
        id: 1,
        plate: "OR-487988",
        type: "car",
        name: "Ford Endeavour",
        fuel_type: "gasoline",
        fuel_capacity: "150",
        manufacturer: "ford",
        model: "Ford EcoSport.",
        note: "For 2015, Acura brought an all-new midsize sports sedan - the TLX. It is the TL successor and it slots right between the ILX entry-luxury sedan and the RLX flagship in the automaker’s refreshed performance lineup.",
        longitude: 38.7578,
        latitude: 8.9806,
        init_odo_value: 15600,
        odo_value: 15700,
        fuel_consumption: 0.6,
      },
      {
        id: 2,
        plate: "AA-00001",
        type: "motorbike",
        name: "name",
        fuel_type: "gasoline",
        fuel_capacity: "500",
        manufacturer: "tesla",
        model: "Model X",
        note: "this is a short note.",
        longitude: 38.7578,
        latitude: 8.9906,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
      {
        id: 3,
        plate: "AA-00002",
        type: "bus",
        name: "ALFA ROMEO",
        fuel_type: "gasoline",
        fuel_capacity: "500",
        manufacturer: "tesla",
        model: "ALFA ROMEO Stelvio Quadrifoglio · ALFA ROMEO MiTo · ALFA ROMEO Giulia GTA",
        note: "this is a short note.",
        longitude: 38.7578,
        latitude: 8.9606,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
      {
        id: 4,
        plate: "AA-00003",
        type: "truck",
        name: "ACURA TLX",
        fuel_type: "gasoline",
        fuel_capacity: "500",
        manufacturer: "ford",
        model: "ACURA TLX 2.0L",
        note: "this is a short note.",
        longitude: 38.7578,
        latitude: 8.9906,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
      {
        id: 5,
        plate: "AA-0005",
        type: "truck",
        name: "Ford Edge",
        fuel_type: "gasoline",
        fuel_capacity: "500",
        manufacturer: "tesla",
        model: "Ford Edge",
        note: "this is a short note.",
        longitude: 38.7678,
        latitude: 8.9796,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
      {
        id: 6,
        plate: "AA-00006",
        type: "bus",
        name: "name",
        fuel_type: "gasoline",
        fuel_capacity: "500",
        manufacturer: "tesla",
        model: "Ford Freestyle",
        note: "this is a short note.",
        longitude: 38.7578,
        latitude: 8.9586,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
      {
        id: 7,
        plate: "AA-0007",
        type: "motorbike",
        name: "Ranger Raptor	",
        fuel_type: "gasoline",
        fuel_capacity: "50",
        manufacturer: "ford",
        model: "Ranger Raptor",
        note: "The discontinued Ford models will be the full-size Taurus sedan, the mid-size Fusion.",
        longitude: 38.7508,
        latitude: 8.9906,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
      {
        id: 8,
        plate: "AA-0008",
        type: "bus",
        name: "name",
        fuel_type: "gasoline",
        fuel_capacity: "500",
        manufacturer: "tesla",
        model: "Model X",
        note: "this is a short note.",
        longitude: 38.7478,
        latitude: 8.9806,
        init_odo_value: 1650,
        odo_value: 1890,
        fuel_consumption: 0.5,
      },
    ];

    let dispatches: Dispatch[] = [
      {
        id: 1,
        vehicle_id: 1,
        plate: "OR-487988",
        driver: "Mesfen",
        init_latitude: 51.678418,
        init_longitude: 7.809007,
        end_latitude: 51.678418,
        end_longitude: 7.809007,
        reason: "No reason just for che..",
        odometer_value: 54000,
      },

      {
        id: 2,
        vehicle_id: 2,
        plate: " AA-00001",
        driver: " Mesafent",
        init_latitude: 51.678418,
        init_longitude: 7.809007,
        end_latitude: 51.678418,
        end_longitude: 7.809007,
        reason: "No reason just for che..",
        odometer_value: 54000,
      },
    ];

    return { vehicles, dispatches };
  }
}
